# Generated by Django 5.1.6 on 2025-03-07 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LexicalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LexicalCategoryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lexical_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.lexicalcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WordClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.language')),
            ],
        ),
        migrations.AddField(
            model_name='lexicalcategory',
            name='word_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.wordclass'),
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
                ('lexical_category_values', models.ManyToManyField(to='lexicon.lexicalcategoryvalue')),
                ('word_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.wordclass')),
            ],
        ),
    ]
