# Generated by Django 5.1.6 on 2025-03-16 19:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_alter_lexicalcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexeme',
            name='coefficient',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lexeme',
            name='last_repetition',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=1)),
                ('translation', models.CharField(max_length=256)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.lexeme')),
            ],
        ),
    ]
