# Generated by Django 5.1.6 on 2025-03-23 15:28

import lexicon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_lexeme_coefficient_lexeme_last_repetition_meaning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'язык', 'verbose_name_plural': 'языки'},
        ),
        migrations.AlterModelOptions(
            name='lexeme',
            options={'verbose_name': 'лексема', 'verbose_name_plural': 'лексемы'},
        ),
        migrations.AlterModelOptions(
            name='lexicalcategory',
            options={'verbose_name': 'лексическая категория', 'verbose_name_plural': 'лексические категории'},
        ),
        migrations.AlterModelOptions(
            name='lexicalcategoryvalue',
            options={'verbose_name': 'значение лексической категории', 'verbose_name_plural': 'значения лексической категории'},
        ),
        migrations.AlterModelOptions(
            name='meaning',
            options={'verbose_name': 'значение', 'verbose_name_plural': 'значения'},
        ),
        migrations.AlterModelOptions(
            name='wordclass',
            options={'verbose_name': 'часть речи', 'verbose_name_plural': 'части речи'},
        ),
        migrations.AddField(
            model_name='lexeme',
            name='next_repetition',
            field=models.DateTimeField(default=lexicon.models.Lexeme.default_next_repetition),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='lexeme',
            name='word',
            field=models.CharField(max_length=256, verbose_name='слово'),
        ),
        migrations.AlterField(
            model_name='lexicalcategory',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='lexicalcategoryvalue',
            name='name',
            field=models.CharField(max_length=128, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='translation',
            field=models.CharField(max_length=256, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='wordclass',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
    ]
